/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package catapalavra;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Irlei
 */
public class Ui extends javax.swing.JFrame {

    /**
     * Creates new form Ui
     */
    int pontos = 0;

    public Ui() {
        initComponents();
        trocarImagem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        imagem = new javax.swing.JLabel();
        texto_da_imagem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        conta_pontos = new javax.swing.JLabel();
        botao_proximo = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagem.setBackground(new java.awt.Color(102, 153, 255));
        imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagem.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 255)));

        texto_da_imagem.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        texto_da_imagem.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        texto_da_imagem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                texto_da_imagemCaretUpdate(evt);
            }
        });
        texto_da_imagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_da_imagemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("PONTOS");

        conta_pontos.setBackground(new java.awt.Color(255, 0, 0));
        conta_pontos.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        conta_pontos.setForeground(new java.awt.Color(255, 0, 0));
        conta_pontos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conta_pontos.setText("0");

        botao_proximo.setBackground(new java.awt.Color(51, 255, 255));
        botao_proximo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botao_proximo.setForeground(new java.awt.Color(0, 0, 255));
        botao_proximo.setText("PRÓXIMO");
        botao_proximo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 5, true));
        botao_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_proximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(texto_da_imagem)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conta_pontos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(botao_proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(imagem, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addGap(22, 22, 22)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addComponent(texto_da_imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(conta_pontos)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(botao_proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );

        jMenu3.setText("Exibir");

        jMenuItem5.setText("Exibir melhor resultado");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar3.add(jMenu3);

        jMenu4.setText("Ajuda");
        jMenu4.setMargin(new java.awt.Insets(2, 25, 2, 2));
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Ajuda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);
        jMenu4.add(jSeparator1);

        jMenuItem2.setText("sobre");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar3.add(jMenu4);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto_da_imagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_da_imagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_da_imagemActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, new Ajuda(), "Ajuda", 1);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, new Info(), "Sobre", 1);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void texto_da_imagemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_texto_da_imagemCaretUpdate
        // TODO add your handling code here:
        if (nomecorreto()) {
            texto_da_imagem.setForeground(Color.RED);
            texto_da_imagem.setEditable(false);
            texto_da_imagem.setBackground(Color.blue);
            pontos++;
            conta_pontos.setText(String.valueOf(pontos));
            this.botao_proximo.setVisible(true);
        } else {
            this.botao_proximo.setVisible(false);
        }

    }//GEN-LAST:event_texto_da_imagemCaretUpdate

    private void botao_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_proximoActionPerformed
        // TODO add your handling code here:
        trocarImagem();
        this.texto_da_imagem.setText(null);
    }//GEN-LAST:event_botao_proximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_proximo;
    private javax.swing.JLabel conta_pontos;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField texto_da_imagem;
    // End of variables declaration//GEN-END:variables
    int pselect;

    private void reset_digitacao() {
        this.texto_da_imagem.setText(null);
        this.texto_da_imagem.setEditable(true);
        this.texto_da_imagem.setBackground(Color.white);
        this.texto_da_imagem.setForeground(Color.black);
    }

    public void trocarImagem() {

        int palavras_count = getArrayPalavras().size();
        if (palavras_count > 0) {
            Random num = new Random();
            pselect = num.nextInt(palavras_count);
            imagem.setIcon(new ImageIcon(getClass().getResource("/imagens/" + getArrayPalavras().get(pselect) + ".jpg")));
            this.texto_da_imagem.grabFocus();

            this.botao_proximo.setVisible(false);
            reset_digitacao();
        }

    }

    private List getArrayPalavras() {
        List<String> nomes_img = new ArrayList<>();
        nomes_img.add("BATEDEIRA");
        nomes_img.add("CADEADO");
        nomes_img.add("CADEIRA");
        nomes_img.add("DINHEIRO");
        nomes_img.add("FOGUEIRA");
        nomes_img.add("SAPATO");
        nomes_img.add("SOLDADO");
        nomes_img.add("TÁBUA");
        nomes_img.add("ASA");
        nomes_img.add("BALÃO");
        nomes_img.add("CAVALO");
        nomes_img.add("CHUVEIRO");
        nomes_img.add("ESQUILO");
        nomes_img.add("ILHA");
        nomes_img.add("JACA");
        nomes_img.add("LÁPIS");
        nomes_img.add("MAÇÃ");
        nomes_img.add("PALHAÇO");
        nomes_img.add("PICOLÉ");
        nomes_img.add("PILHA");
        nomes_img.add("PIÃO");
        nomes_img.add("PRATO");
        nomes_img.add("RATO");
        nomes_img.add("RELÓGIO");
        nomes_img.add("TATU");
        nomes_img.add("TUCANO");
        nomes_img.add("UVAS");
        nomes_img.add("VACA");
        return nomes_img;
    }

    private boolean nomecorreto() {

        if (this.texto_da_imagem.getText() == null) {
            return false;
        }

        return getArrayPalavras().get(pselect).equals(this.texto_da_imagem.getText().toUpperCase());
    }
}
