/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Dao.Palavra;
import Dao.Sessao;
import javax.swing.JOptionPane;

/**
 *
 * @author Irlei
 */
public class CadastroPalavra extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPalavra
     */
    private Sessao sessao;
    private Palavra palavra;
    private int novo_tema = 0;

    public CadastroPalavra(Sessao sessao) {
        initComponents();
        this.sessao = sessao;
        popularcombTemas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox_tema = new javax.swing.JComboBox();
        jTextField_texto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_nivel = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButton_adicionar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jButton_novo_tema = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Texto :");

        jComboBox_tema.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jTextField_texto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_textoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Nível :");

        jComboBox_nivel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox_nivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "1", "2", "3", "4", "5" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Tema :");

        jButton_adicionar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_adicionar.setText("Adicionar");
        jButton_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_adicionarActionPerformed(evt);
            }
        });

        jButton_cancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_cancelar.setText("Fechar");
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });

        jButton_novo_tema.setText("Novo tema");
        jButton_novo_tema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_novo_temaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton_novo_tema)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_texto)
                    .addComponent(jComboBox_tema, 0, 433, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_adicionar)
                                .addGap(120, 120, 120)
                                .addComponent(jButton_cancelar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_novo_tema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_adicionar)
                    .addComponent(jButton_cancelar))
                .addGap(20, 20, 20))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-577)/2, (screenSize.height-361)/2, 577, 361);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_textoActionPerformed

    private void jButton_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_adicionarActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            this.palavra = new Palavra();
            palavra.setNivel(this.jComboBox_nivel.getSelectedIndex());
            palavra.setTexto(jTextField_texto.getText());
            palavra.setTema(jComboBox_tema.getSelectedIndex());
            salvar();
        }
    }//GEN-LAST:event_jButton_adicionarActionPerformed

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_cancelarActionPerformed

    private void jButton_novo_temaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_novo_temaActionPerformed
        // TODO add your handling code here
        getNovoTema().setVisible(true);
        novo_tema++;

    }//GEN-LAST:event_jButton_novo_temaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_adicionar;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JButton jButton_novo_tema;
    private javax.swing.JComboBox jComboBox_nivel;
    private javax.swing.JComboBox jComboBox_tema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField_texto;
    // End of variables declaration//GEN-END:variables
    private AddTema novoTema;

    private void salvar() {
        this.sessao.addPalavra(palavra);
        if (this.novo_tema != 0) {
            this.sessao.addTema((String) this.jComboBox_tema.getItemAt(this.jComboBox_tema.getItemCount() - 1));
            this.novo_tema = 0;
        }
        JOptionPane.showMessageDialog(null, "Pronto!");
        limpar();
    }

    private void limpar() {
        //this.jComboBox_nivel.setSelectedIndex(0);
        //this.jComboBox_tema.setSelectedIndex(0);
        this.jTextField_texto.setText(null);

    }

    private boolean validar() {
        String nivel = this.jComboBox_nivel.getSelectedItem().toString();
        String texto = this.jTextField_texto.getText();
        String tema = this.jComboBox_tema.getSelectedItem().toString();

        if (texto != null && !texto.equals("") && !nivel.equals("--") && !tema.equals("----")) {
            return true;
        } else {
            return false;
        }
    }

    public void popularcombTemas() {
        this.jComboBox_tema.addItem("----");
        for (String s : this.sessao.getTemas()) {
            this.jComboBox_tema.addItem(s);
        }

    }

    public AddTema getNovoTema() {
        if (this.novoTema == null) {
            this.novoTema = new AddTema(this.jComboBox_tema);
        }

        return novoTema;
    }
}
