/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Dao.Aluno;
import Dao.Sessao;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;

/**
 *
 * @author Irlei
 */
public class EscolherJogador extends javax.swing.JFrame {

    /**
     * Creates new form EscolherJogador
     */
    private Sessao sessao;
    private JLabel label_jogador;

    public EscolherJogador(Sessao sessao, JLabel label) {
        initComponents();
        this.label_jogador = label;
        this.sessao = sessao;

        if (sessao.getAlunos() != null) {
            for (Aluno al : sessao.getAlunos()) {
                this.jComboBox_jogador.addItem(al);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_jogador = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Jogador");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jComboBox_jogador.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jComboBox_jogador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Procure seu nome:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox_jogador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jButton1)
                .addGap(0, 289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jComboBox_jogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-649)/2, (screenSize.height-297)/2, 649, 297);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (this.jComboBox_jogador.getSelectedIndex() > 0) {
            this.sessao.setJogador(getJogador());
            this.label_jogador.setText(this.sessao.getJogador().toString());
        }

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox_jogador;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public Aluno getJogador() {
        return (Aluno) this.jComboBox_jogador.getSelectedItem();
    }

    public void atualizar(Sessao s) {

        if (s.getAlunos() != null) {
            jComboBox_jogador.removeAllItems();
            jComboBox_jogador.addItem("----");
            for (Aluno al : sessao.getAlunos()) {
                this.jComboBox_jogador.addItem(al);
            }
            this.jComboBox_jogador.setSelectedItem(s.getJogador());

        }
    }
}
